#!/usr/bin/env python3
"""Embed light/shaders/*.{vert,frag} into a C header.

Shaders are source code, and a game should not have to ship loose .glsl
files next to its binary — so the GLSL is compiled into the executable as
string literals. This generates that header; the result is committed, so
building the project needs no Python.

Regenerate after editing any shader:

    python3 scripts/embed_shaders.py

`tests/light` checks the committed header still matches the sources, the
same way bindgen_freshness guards the generated bindings.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SHADER_DIR = REPO / "light" / "shaders"
OUTPUT = REPO / "light" / "src" / "light_shaders.h"

HEADER = """/*
 * light_shaders.h — GENERATED by scripts/embed_shaders.py. Do not edit.
 *
 * The GLSL sources in light/shaders/ as string literals, so a game ships
 * one binary with no shader files beside it.
 *
 * The sources carry no #version line: the loader prepends one, because the
 * same shader has to serve desktop GL (120) and GLES/WebGL (100).
 */
#ifndef SDLSTATIC_LIGHT_SHADERS_H
#define SDLSTATIC_LIGHT_SHADERS_H

"""

FOOTER = """
#endif /* SDLSTATIC_LIGHT_SHADERS_H */
"""


def escape(line: str) -> str:
    return line.replace("\\", "\\\\").replace('"', '\\"')


def read_lines(path: Path) -> list[str]:
    # Bytes, not text: a Windows checkout may have CRLF line endings, and
    # the committed header has to compare equal on every platform.
    text = path.read_bytes().replace(b"\r\n", b"\n").decode("utf-8")
    return text.split("\n")


def emit(name: str, path: Path) -> str:
    out = [f"static const char {name}[] =\n"]
    lines = read_lines(path)
    if lines and lines[-1] == "":
        lines.pop()  # trailing newline, not a blank line
    for line in lines:
        out.append(f'    "{escape(line)}\\n"\n')
    out.append("    ;\n")
    return "".join(out)


def build() -> str:
    parts = [HEADER]
    for path in sorted(SHADER_DIR.iterdir()):
        if path.suffix not in (".vert", ".frag"):
            continue
        name = "k" + "".join(p.title() for p in path.stem.split("_")) + path.suffix.title()[1:]
        # as_posix(): a Windows path renders with backslashes, which would
        # make the committed header differ there and nowhere else.
        parts.append(f"/* {path.relative_to(REPO).as_posix()} */\n")
        parts.append(emit(name, path))
        parts.append("\n")
    parts.append(FOOTER)
    return "".join(parts)


def main() -> int:
    text = build()
    fresh = text.encode("utf-8")
    if "--check" in sys.argv:
        current = OUTPUT.read_bytes().replace(b"\r\n", b"\n") if OUTPUT.exists() else b""
        if current != fresh:
            print("light_shaders.h is stale; run scripts/embed_shaders.py", file=sys.stderr)
            return 1
        print("light_shaders.h is up to date")
        return 0
    # newline="" so the LF above survives on Windows too.
    with OUTPUT.open("w", encoding="utf-8", newline="") as handle:
        handle.write(text)
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
